spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wshop
    username: root
    password: 123456
    # kebab case
    driver-class-name: com.mysql.cj.jdbc.Driver
    # snake case
    # driver_class_name
    # camel case
    # driverClassName
mybatis:
  config-location: classpath:db/mybatis/config.xml
